name: Setup Android CI
description: Configure Rust, just, sccache, and Java for Android CI.

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: ./.github/actions/setup-rust-ci

    - name: Setup Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        distribution: temurin
        java-version: "17"
