package com.gemwallet.android.ui.icons

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.res.vectorResource
import com.gemwallet.android.ui.R

object AppIcons {
    val Send: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_send)
    val Receive: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_receive)
    val Buy: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_buy)
    val Swap: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_swap)
    val Deposit: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_deposit)
    val Withdraw: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_action_withdraw)

    val Add: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_add)
    val AddCircleOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_add_circle_outlined)
    val ArrowBack: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_arrow_back)
    val ArrowCircleDown: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_arrow_circle_down)
    val ArrowCircleUp: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_arrow_circle_up)
    val ArrowDownward: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_arrow_downward)
    val ArrowUpward: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_arrow_upward)
    val Article: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_article)
    val Camera: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_camera)
    val Cancel: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_cancel)
    val Check: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_check)
    val CheckCircle: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_check_circle)
    val CheckCircleOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_check_circle_outlined)
    val Close: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_close)
    val ContentCopy: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_content_copy)
    val ContentCopyOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_content_copy_outlined)
    val ContentPaste: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_content_paste)
    val CurrencyBitcoin: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_currency_bitcoin)
    val Delete: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_delete)
    val ElectricBolt: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_electric_bolt)
    val EmojiEvents: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_emoji_events)
    val Error: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_error)
    val ExpandMore: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_expand_more)
    val FilterAlt: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_filter_alt)
    val History: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_history)
    val Image: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_image)
    val ImageOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_image_outlined)
    val Info: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_info)
    val InfoOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_info_outlined)
    val KeyboardArrowDown: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_keyboard_arrow_down)
    val KeyboardArrowRight: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_keyboard_arrow_right)
    val MoreVert: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_more_vert)
    val Notifications: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_notifications)
    val NotificationsOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_notifications_outlined)
    val PushPin: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_push_pin)
    val QrCodeScanner: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_qr_code_scanner)
    val Refresh: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_refresh)
    val Search: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_search)
    val Settings: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_settings)
    val SettingsOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_settings_outlined)
    val Share: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_share)
    val ShowChart: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_show_chart)
    val StarOutlined: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_star_outlined)
    val SwapVert: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_swap_vert)
    val Tune: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_tune)
    val Verified: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_verified)
    val Visibility: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_visibility)
    val VisibilityOff: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_visibility_off)
    val Wallet: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_wallet)
    val Warning: ImageVector @Composable get() = ImageVector.vectorResource(R.drawable.ic_warning)
}
