name: Android Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  unit_test:
    name: Unit Tests
    runs-on: macos-26
    env:
      UNIT_TESTS: "true"
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Setup Android CI
        uses: ./.github/actions/setup-android-ci

      - name: Bootstrap
        run: just bootstrap

      - name: Clean Android build outputs
        run: just clean

      - name: Build
        run: just build
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: just test
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
