name: Core Unit Tests

on:
  push:
    branches: ["main"]
    paths:
      - "core/**"
      - ".github/actions/setup-rust-ci/**"
      - ".github/workflows/core-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "core/**"
      - ".github/actions/setup-rust-ci/**"
      - ".github/workflows/core-ci.yml"

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  unit_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Rust
        uses: ./.github/actions/setup-rust-ci

      - name: Run tests
        run: just test

  integration_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Rust
        uses: ./.github/actions/setup-rust-ci

      - name: Build all integration tests only
        run: just build-integration-tests

      - name: Check gemstone dependencies
        run: |
          cargo tree --package gemstone | grep -i reqwest && exit 1 || echo "✓ No reqwest dependencies found in gemstone"
