name: iOS Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit_test:
    name: Build and Test iPhone simulator
    runs-on: [self-hosted, macOS]

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive

      - name: Install dependencies
        working-directory: ios
        run: just install-toolchains

      - name: Build Core
        working-directory: ios
        run: just generate-stone

      - name: Resolve SPM Dependencies
        working-directory: ios
        run: just spm-resolve

      - name: Build for Testing
        working-directory: ios
        run: just build-for-testing

      - name: Unit Tests
        working-directory: ios
        run: just test-without-building
