name: iOS Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  unit_test:
    name: Build and Test iPhone simulator
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive

      - name: Setup iOS CI
        uses: ./.github/actions/setup-ios-ci

      - name: Install dependencies
        working-directory: ios
        run: just install-toolchains

      - name: Build Core
        working-directory: ios
        run: just generate-stone

      - name: Resolve SPM Dependencies
        working-directory: ios
        run: just spm-resolve

      - name: Build for Testing
        working-directory: ios
        run: just build-for-testing

      - name: Unit Tests
        working-directory: ios
        run: just test-without-building
